# Generated by Django 4.2.2 on 2023-06-20 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='наименование')),
                ('description_product', models.TextField(verbose_name='описание')),
                ('picture_product', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение')),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='цена за покупку')),
                ('date_of_creation_product', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('last_modified_date_product', models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
