# Generated by Django 4.2.2 on 2023-06-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture_category',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение'),
        ),
    ]
