# Generated by Django 4.2.2 on 2023-06-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_category_picture_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture_category',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='изображение'),
        ),
    ]
