# Generated by Django 4.2.2 on 2023-07-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
