# Generated by Django 4.2.2 on 2023-07-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
